### ISSUE TITLE
Why did you use "else:" in line 41?

### ISSUE THREAD

**Issue by wragon** [jihwanp/CPC_HOTR#1]
[line41](https://github.com/jihwanp/CPC_HOTR/blob/main/hotr/data/datasets/hico.py#L41)

Why did you use "else:" in line 41?
Doesn't it work the same without using "else:"?

**Comment by wragon** [comment]
Is this optional "else:" clause by "if:" statement of Line 39?

**Comment by wragon** [comment]
Is this optional "else:" clause by "if:" statement of [Line39](https://github.com/jihwanp/CPC_HOTR/blob/main/hotr/data/datasets/hico.py#L39)?

**Comment by jihwanp** [comment]
Hi, the dataloader scripts are all based on the implementation of HOTR. Please contact the author of HOTR.
